### ISSUE TITLE
Will the package be created automatically with correct permissions?

### ISSUE THREAD

**Issue by jtherrmann** [ASFHyP3/hyp3-cookiecutter#36]
While creating the https://github.com/ASFHyP3/hyp3-isce2 plugin, we ran into an issue where the GitHub package had already been created and did not have correct permissions set to allow the build workflow to push the Docker image, see here: https://github.com/ASFHyP3/hyp3-isce2/issues/3#issuecomment-1483584542

I want to know if everything would have worked if the package had not already been created; would the package be created automatically with the correct permissions? If not, we should document the steps for setting the correct perms.

**Comment by jhkennedy** [comment]
When the package is initially pushed to GitHub, it's expected that the actions will fail (documented in README) due to permissions errors. Once all the steps in the readme have been completed and the workflows restarted, they should all work:
https://github.com/ASFHyP3/hyp3-cookiecutter?tab=readme-ov-file#hyp3-cookiecutter


I'm going to close this as done, but please re-open if anyone runs into this again.
