### ISSUE TITLE
Project names that do not include `hyp3` cause pyproject.toml failure

### ISSUE THREAD

**Issue by forrestfwilliams** [ASFHyP3/hyp3-cookiecutter#9]
Currently the cookiecutter assumes that the project's name begins with `Hyp3-` otherwise it will break in subtle ways when provided the default names. Do we want to enforce this assumption, or allow people to create a wider variety of project names?

**Comment by jtherrmann** [comment]
We were getting an error when attempting to `pip` install the resulting package when `package_name` and `process_name` are the same, because this results in two entrypoints in `pyproject.toml` with the same name. This happened when we would choose a package name that did not include `hyp3`, because then there would be no occurrence of `hyp3` to be replaced by `proc` (see https://github.com/ASFHyP3/hyp3-cookiecutter/blob/update_staging/cookiecutter.json#L7) so then package name and process name would end up the same.

We fixed this with https://github.com/ASFHyP3/hyp3-cookiecutter/pull/8/commits/3ec72b02b3bf8bd397745b1ab717189733e08997 by forbidding the user from setting package name and process name the same. This may be sufficient to close this issue, but we may still want to think more about whether we are giving the user too many choices for customization (see https://github.com/ASFHyP3/hyp3-cookiecutter/blob/update_staging/cookiecutter.json) and whether we should perhaps handle more of that stuff behind the scenes.

**Comment by jtherrmann** [comment]
Right now, this is most likely to occur to someone when they leave out `hyp3` from their `project_name`, and the error message (`ERROR: package_name and process_name must be different!`) is probably not very helpful.

**Comment by jhkennedy** [comment]
Oh, this is a good question! 

I think we can drop the console script entry points entirely, eliminating the `pyproject.toml` issue -- see: #10 

But it's worth thinking about the name and prompts overall. 

Typically, we've followed the pattern:
* Repo: `hyp3-<name>` (`cookiecutter.project_name`)
* Human readable name: `HyP3 Name` (`cookiecutter.project_title`)
* Python package: `hyp3_<name>` (`cookiecutter.package_name`)

This is a good pattern overall, I think, for plugins and would want to "strongly suggest" but not necessarily enforce (e.g., RAiDER was an existing package we added HyP3 functionality to). Though for a plugin cookie-cutter, do we want to enforce a hyp3 prefix?

The next part, I've always disliked what I settled on, and I don't know if there's a good convention for it. 

There's 
* a "Science" function that gets executed by the main entry point: https://github.com/ASFHyP3/hyp3-cookiecutter/blob/update_staging/%7B%7Bcookiecutter.project_name%7D%7D/src/%7B%7Bcookiecutter.package_name%7D%7D/__main__.py#L31-L33
* which lives in the `process.py` module: https://github.com/ASFHyP3/hyp3-cookiecutter/blob/update_staging/%7B%7Bcookiecutter.project_name%7D%7D/src/%7B%7Bcookiecutter.package_name%7D%7D/process.py

I want users to be able to name this function appropriately (descriptively), so we should likely prompt for that name, so we added:
* "Science" process function name: `proc_<name>` (`cookiecutter.process_name`)
* Human readable process name: `<name>` (`cookiecutter.process_type`)

The `process_type` is only used to populate the [`__main__` docstring](https://github.com/ASFHyP3/hyp3-cookiecutter/blob/update_staging/%7B%7Bcookiecutter.project_name%7D%7D/src/%7B%7Bcookiecutter.package_name%7D%7D/__main__.py#L2) and the [`process.py` module docstring](https://github.com/ASFHyP3/hyp3-cookiecutter/blob/update_staging/%7B%7Bcookiecutter.project_name%7D%7D/src/%7B%7Bcookiecutter.package_name%7D%7D/process.py#L2)

**Comment by jhkennedy** [comment]
:thinking: The minimal description of a hyp3-plugin is: 

> A HyP3 plugin runs a process (workflow) that creates a product and uploads it to AWS S3. 

maybe we should do something like:
* prompt for a "product name" (`cookiecutter.product_name`), and then from there assume:
  * Repo: `hyp3-{{cookiecutter.product_name |replace('_', '- ') }}>`
  * Human readable name: `HyP3 {{cookiecutter.product_name |replace('_', ' ') | title }}`
  * Python package: `hyp3_{{cookiecutter.product_name}}`
  * process (workflow) function name: `make_{{cookiecutter.product_name}}`
  
and it might even make sense to rename `process.py` `workflow.py`. 
  
If we ensured `product_name` conformed to a [python package regex](https://github.com/ASFHyP3/hyp3-cookiecutter/blob/update_staging/hooks/pre_gen_project.py#L5), we could even *not* prompt for any of the sub-bullets.
